<?php
defined('_JEXEC') or die;

class TopicViewTopics extends JViewLegacy{
    public function display($tpl = null)
    {
        $this->addTollBar();
        parent::display($tpl); // TODO: Change the autogenerated stub
    }
    public function addTollBar(){
        $title = JText::_('COM_TOPIC_MANAGER_TOPICS');



        JToolBarHelper::title($title, 'helloworld');

        JToolBarHelper::deleteList('', 'topics.delete');
        JToolBarHelper::editList('topic.edit');
        JToolBarHelper::addNew('topic.add');
    }
}